from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

def write_work_exp():
    p = document.add_paragraph()

    company = input('Enter company: ')
    from_date = input('From Date: ')
    to_date = input('To Date: ')

    p.add_run(company + ' ').bold = True
    p.add_run(from_date + '-' + to_date + '\n').italic = True

    experience_details = input('Describe your experience at ' + company + ' ')
    p.add_run(experience_details)

document = Document()

# profile picture
document.add_picture("girlSmile.jpg", width=Inches(2.0))

# name, ph num, email details
name = input('What is your name? ')
speak('Hello ' + name + 'how are you today?')
phone_num = input('What is your phone number? ')
email = input('Email? ')

document.add_paragraph(
    name + ' | ' + phone_num + ' | ' + email)

# about me
document.add_heading('About Me')
document.add_paragraph(input('Tell me about yourself: '))

# work experience
write_work_exp()

# more experiences
while True:
    has_more_exp = input('Do you have more experiences? Yes or No: ')
    if has_more_exp.lower() == 'yes':
        write_work_exp()
    else:break

# skills
document.add_heading('Skills')
skill = input('Enter skill: ')
p = document.add_paragraph(skill)
p.style = 'List Bullet'

while True:
    has_more_skills = input('Do you have more skills? Yes or No: ')
    if has_more_skills.lower() == 'yes':
        skill = input('Enter skill: ')
        p = document.add_paragraph(skill)
        p.style = 'List Bullet'
    else:
        break

# footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = "CV generated by learning."

document.save('cv.docx')